package com.eulen.flexinet.core.test.selenium.Locators;

public enum FieldByTagLabelText {

    A("A:"),
    ACTIVIDAD("Actividad:"),
    APELLIDOS("Apellidos:"),
    ATURNOS("A turnos"),
    AVALNECESARIO("Aval Necesario"),
    BANCO("Banco:"),
    BOE("BOE"),
    BONIFICACION("Bonificación:"),
    BRUTOMENSUAL("Bruto Mensual"),
    BTN_ACEPTAR("Aceptar"),
    BTN_IMPRIMIR ("Imprimir"),
    BTN_ANADIR("Añadir"),
    BTN_ANADIRCATEGORIA("Añadir Categoría"),
    BTN_ANADIRCONCEPTO("Añadir Concepto"),
    BTN_ANADIRCONTACTO("Añadir Contacto"),
    BTN_ANADIRIT("Añadir IT"),
    BTN_ANADIRPARTE("Añadir Parte"),
    BTN_ANULARCONTRATO("Anular Contrato"),
    BTN_ANULARPRORROGA("Anular Prórroga"),
    BTN_ASOCIARAEMPRESA("Asociar a Empresa"),
    BTN_ASOCIARCOLABORADOR("Asociar Colaborador"),
    BTN_BAJACONTRATOS("Baja de Contratos"),
    BTN_MARCAR_ENVIADO("Marcar como Enviado"),
    BTN_MARCAR_RECIBIDO("Marcar como Recibido"),
    BTN_BORRAR_IT("Borrar IT"),
    BTN_BUSCAR("Buscar"),
    BTN_BUSCAREMPRESA("Buscar Empresa"),
    BTN_BUSCARCOLABORADOR("Buscar Colaborador"),
    BTN_BUSQUEDARAPIDA("Búsqueda Rápida"),
    BTN_CANCELAR("Cancelar"),
    BTN_CREARPARTEDEHORAS("Crear Parte de Horas"),
    BTN_CREARPRORROGA("Crear Prórroga"),
    BTN_DARDEBAJA("Dar de Baja"),
    BTN_ANULARBAJA("Anular Baja"),
    BTN_ALTADESUSTITUCION("Alta de Sustitución"),
    BTN_ALTASUSTITUCION("Alta Sustitución"),
    BTN_DESBLOQUEAR("Desbloquear"),
    BTN_EDITARPEDIDO("Editar Pedido"),
    BTN_ELIMINAR("Eliminar"),
    BTN_ELIMINARCONCEPTO("Eliminar Concepto"),
    BTN_ELIMINARLINEA("Eliminar Línea"),
    BTN_ENVIARARIESGOS("Enviar a Riesgos"),
    BTN_FINALIZAR("Finalizar"),
    BTN_GENERARCONTRATOS("Generar Contratos"),
    BTN_GRABAR("Grabar"),
    BTN_GUARDAR("Guardar"),
    BTN_GUARDARTRASPASAR("Guardar Traspasar"),
    BTN_GUARDARYTRASPASAR("Guardar Y Traspasar"),
    BTN_MODIFICAR("Modificar"),
    BTN_MODIFICAREMPRESA("Modificar Empresa"),
    BTN_MOSTRARCONTRATOS("Mostrar Contratos"),
    BTN_MOSTRAREMPRESAS("Mostrar Empresas"),
    BTN_NOVARCONTRATO("Novar Contrato"),
    BTN_OBTENERDATOS("Obtener Datos"),
    BTN_OK("OK"),
    BTN_PERFILDATOUNICO("Perfil Dato Único"),
    BTN_PRESENTARINFORME("Presentar Informe"),
    BTN_SI("Sí"),
    BTN_SI_CONTRATO("Si"), //TODO REVISAR PARA QUE SE USE SI_SINACENTO
    BTN_SI_SINACENTO("Si"),
    BTN_TRASPASAR("Traspasar"),
    BTN_TRASPASARERP("Traspasar a Erp"),
    BTN_TRASPASARAORACLE("Traspasar a Oracle"),
    BTN_TRASPASOMASIVO("Traspaso Masivo"),
    BTN_VERDETALLECONTRATO("Ver Detalle Contrato"),
    BTN_VEREMPRESA("Ver Empresa"),
    BUSQUEDAANIVELNACIONAL("Búsqueda a Nivel Nacional"),
    BUSQUEDAASOCIADA("Búsqueda Asociada:"),
    CARACTERISTICASDETARIFA("Características de Tarifa:"),
    CARGO("Cargo:"),
    CATEGORIALABORAL("Categoría Laboral:"),
    CATEGORIAPROFESIONAL("Categoría Profesional:"),
    CENTROSDETRABAJO("Centros de Trabajo:"),
    CERTIFICADOPROFESIONAL("Certificado Profesional:"),
    CHK_ABONOSPARCIALES("Abonos Parciales"),
    CHK_ABONOSTOTALES("Abonos Totales"),
    CHK_ACTIVOS("Activos"),
    CHK_ANIVELNACIONAL("A Nivel Nacional"),
    CHK_BAJAS("Bajas"),
    CHK_BUSCARANIVELNACIONAL("Buscar a Nivel Nacional"),
    CHK_BUSQUEDAANIVELNACIONAL("Búsqueda a Nivel Nacional"),
    CHK_BUSQUEDAERP("Búsqueda ERP"),
    CHK_CESEVOLUNTARIO("Cese voluntario"),
    CHK_CLIENTESNACIONAL("Clientes Nacional"),
    CHK_COLABORADORCONCEPTO("Colaborador / Concepto"),
    CHK_CONPRORROGAS("Con Prórrogas"),
    CHK_DENTRORANGOFECHAS("Dentro del Rango de Fechas:"),
    CHK_DIARIO("Diario"),
    CHK_DIFERENCIA("Diferencia:"),
    CHK_DIFERENCIA2("Diferencia"),
    CHK_ELTIPODEFACTURACIONESPERSONALIZABLE("El Tipo de Facturación es Personalizable"),
    CHK_ENVIOCPD("Envío CPD"),
    CHK_ENVIOFACTURADIGITAL("Envío Factura Digital"),
    CHK_ESPECIALES("Especiales"),
    CHK_EXCLUIRGENERADOS("Excluir Generados"),
    CHK_FACTURADASMANUALES("Facturas Manuales"),
    CHK_FACTURAGLOBALIZADA("Factura Globalizada"),
    CHK_FACTURAS("Facturas"),
    CHK_FIRMANTECPDPRLPERSONALIZABLE("Firmante CPD, PRL Personalizable"),
    CHK_GENERADOS("Generados"),
    CHK_LAEMPRESAPROVIENEDEMARKETING("La Empresa Proviene de Marketing"),
    CHK_LLAMAMIENTO("Llamamiento"),
    CHK_MARCARDESMARCAREMITIR("Marcar/Desmarcar para Emitir"),
    CHK_MOSTRARMINFINICIOMAXFFINPARTES("Mostrar Min. F.Inicio / Máx F.Fin Partes"),
    CHK_MOSTRARPRECIOUNIDAD("Mostrar Precio / Unidad"),
    CHK_MOSTRAR_GENERADOS("Mostrar Generados"),
    CHK_NOVACION("Novación"),
    CHK_OFERTA("Oferta"),
    CHK_PARCIAL("Parcial"),
    CHK_PARTESINTRASPASAR("Parte Sin Traspasar"),
    CHK_PARTESENVIADOSAORACLE("Partes enviados a Oracle"),
    CHK_PEDIDOSYAGESTIONADOS("Pedidos Ya Gestionados"),
    CHK_PERSONALIZABLE("Personalizable"),
    CHK_PORCATEGORIAPROFESIONAL("Por Categoría Profesional"),
    CHK_PORCENTROSDETRABAJO("Por Centros de Trabajo"),
    CHK_PORCOLABORADOR("Por Colaborador"),
    CHK_PORDEPARTAMENTOALQUESEINCORPORARAELCOLABORADORENELCENTRODETRABAJO("Por Departamento al que se Incorporará el Colaborador en el Centro de Trabajo"),
    CHK_PORDURACIONDELCONTRATO5DIAS5DIAS("Por Duración del Contrato ( <=5 días >5 días )"),
    CHK_PORIMPORTEGLOBAL("Por Importe Global"),
    CHK_PORNUMERODECOLABORADORES("Por Número de Colaboradores"),
    CHK_PORTIPOSDEHORAS("Por Tipos de Horas"),
    CHK_PREFACTURAS("Prefacturas"),
    CHK_PRLPERSONALIZABLE("PRL Personalizable"),
    CHK_RAPPEL("Rappel"),
    CHK_REALIZARBUSQUEDAANIVELNACIONAL("Realizar la Búsqueda a Nivel Nacional"),
    CHK_SPF("SPF"),
    CHK_TODOSVALIDADOS("Marcar / Desmarcar Todos Como Validados"),
    CHK_TRASPASADOS("Traspasados"),
    CHK_ULTIMOMES("En el Último Mes"),
    CHK_VALIDADASEMISIONMASIVA("Validadas (Emisión Masiva)"),
    CHK_VALIDADO("Validado"),
    CIF("CIF:"),
    CLAUSULADODELCONTRATOLABORAL("Clausulado del Contrato Laboral:"),
    CLAUSULADODELCPD("Clausulado del CPD:"),
    CLAUSULAS("Cláusulas"),
    CLIENTECONTRATO("Cliente Contrato:"),
    CLIENTENACIONAL("Cliente Nacional:"),
    CNAE("CNAE:"),
    CODIGOPOSTAL("Código Postal:"),
    COEFICIENTE("Coeficiente:"),
    COMPPAGO("Comp. Pago:"),
    CONCEPTO("Concepto:"),
    CONTRATACION100("Contratación < 100%"),
    CONTRATACIONMENOS100("Contratación < 100%"),
    CONTRATOLABORAL("Contrato Laboral"),
    CONVCOLECTIVOEMPRESAUSUARIA("Conv. Colectivo Empresa Usuaria:"),
    CONVCOLECTIVOEMPRESAUSUARIA2("Conv.Colectivo Empresa Usuaria:"),
    CONVENIO("Convenio:"),
    CP("C.P.:"),
    CRITERIOSDEBUSQUEDARAPIDADECOLABORADORES("Criterios de Búsqueda Rápida de Colaboradores"),
    DAD_CENTROSDETRABAJO_ASIGNADOS("Asignados"),
    DAD_CENTROSDETRABAJO_DISPONIBLES("Disponibles"),
    DATE_DESDE("Desde:"),
    DATE_DESDE_SIN_PUNTOS("Desde"),
    DATE_FECHABAJA("Fecha de Baja:"),
    DATE_FECHAFINALIZACIONPRORROGA("Fecha de Finalización de Prórroga:"),
    DATE_FECHAFINDESDE("Fecha de Fin Desde:"),
    DATE_FECHAFINHASTA("Fecha de Fin Hasta:"),
    DATE_FECHAFINIT("Fecha de Fin de la IT"),
    DATE_FECHAINICIODEIT("Fecha de Inicio de la IT"),
    DATE_FECHAINICIODESDE("Fecha de Inicio Desde:"),
    DATE_FECHAINICIOHASTA("Fecha de Inicio Hasta:"),
    DATE_FECHAINICIOSUSTITUCION("Fecha de Inicio de la Sustitución:"),
    DATE_HASTA("Hasta:"),
    DATE_HASTA_SIN_PUNTOS("Hasta"),
    DATE_INTRODUZCAFECHAANTIGUEDADCONTRATO("Introduzca la fecha de antigüedad del contrato"),
    DATOSIBANETT("Datos IBAN ETT"),
    DC("DC:"),
    DE("De:"),
    DEPARTAMENTO("Departamento:"),
    DESCRIPCION("Descripción:"),
    DESEMPLEADOYMENOR30ANOS("Desempleado y Menor 30 años:"),
    DESEMPLEADOYMENOR35ANOSYCONDISCAPACSUP30("Desempleado y Menor 35 años y con Discapac. Sup. 30%:"),
    DESTINATARIO("Destinatario:"),
    DEUDAASEGURADA("Deuda Asegurada"),
    DEVENGO("Devengo:"),
    DIASDETRABAJOSEMANALES("Días de Trabajo Semanales:"),
    DIASFIJOSDEPAGO("Días Fijos de Pago:"),
    DIASTRABAJADOSALASEMANA("Días Trabajados a la Semana:"),
    DIRECCION("Dirección:"),
    DIRECCIONDEFACTURA("Dirección de Factura"),
    DIVISIONCOMERCIAL("División Comercial:"),
    DNI("DNI:"),
    NUMEROCONTRATO("Nº Contrato"),
    DNICOLABORADOR("DNI Colaborador:"),
    DOMICILIOFISCAL("Domicilio Fiscal:"),
    DOMICILIOSOCIAL("Domicilio Social:"),
    EJECUTIVODECUENTA("Ejecutivo de Cuenta:"),
    ELEGIRMPIORESIDENCIA("Elegir Mpio. Residencia"),
    ELEGIROCUPACION("Elegir Ocupación"),
    ELEGIRPAISDENACIONALIDAD("Elegir País de Nacionalidad"),
    ELLATRABAJADORAACREDITACONLACERTIFICACIONPOR("El/La Trabajador/a Acredita con la Certificación por:"),
    ELLATRABAJADORAESTAENPOSESIONDELTITULO("El/La Trabajador/a está en posesión del Título:"),
    EMAIL("E-mail:"),
    EMPRESA("Empresa:"),
    EMPRESACLIENTERAZONSOCIAL("Empresa Cliente Razón Social:"),
    ENTIDAD("Entidad:"),
    ESTADO("Estado:"),
    EXISTECONVCOLECTQUEPERMITACONTRATOSDE6A12MESESENUNPERIODODE18("Existe Conv.Colect. que Permita Contratos de 6 a 12 meses en un Período de 18"),
    MARQUESIEXISTECONVCOLECTQUEPERMITACONTRATOSDE6A12MESESENUNPERIODODE18("Marque si Existe Conv.Colect. que Permita Contratos de 6 a 12 meses en un Período de 18"),
    FACTURACION("Facturación"),
    FACTURAS("Facturas:"),
    FECHA("Fecha:"),
    INTRODUCIR_FECHA("Introducir fecha:"),
    FECHAFIN("Fecha Fin:"),
    FECHAINICIO("Fecha Inicio:"),
    FECHAINICIOVIGENCIA("Fecha Inicio Vigencia:"),
    FECHAPREVISATADEFIN("Fecha Prevista de Fin:"),
    FECHAPREVISTADEFIN("Fecha Prevista de Fin:"),
    FECHAPREVISTADEINICIO("Fecha Prevista de Inicio:"),
    FIN("Fin:"),
    FIRMANTESDELCPDYPRL("Firmantes del CPD y PRL:"),
    FORMADEPAGO("Forma de Pago:"),
    FORMATOCLCLAU("Formato CL (Clau.):"),
    FORMATOCPDCLAU("Formato CPD (Clau.):"),
    GENERAR_PARTES("Generar Partes"),
    GRUPO("Grupo:"),
    GRUPOCOTIZACION("Grupo Cotización:"),
    HABERTERMINADOLOSESTUDIOSQUELECAPACITANPARALAPRACTICAOBJETODEDICHOCONTRATOCONFECHA("Haber Terminado los Estudios que le Capacitan para la Práctica, objeto de dicho Contrato, con Fecha:"),
    HASTA("Hasta:"),
    HORARIO("Horario:"),
    HORASCOMPLEMENTARIAS("Horas Complementarias:"),
    HORASEXTRAS("Horas Extras:"),
    HORASFESTIVAS("Horas Festivas:"),
    HORASNOCTURNAS("Horas Nocturnas:"),
    HORASNORMALES("Horas Normales:"),
    HORASNORMALESDIARIAS("Horas Normales Diarias:"),
    HORASPERMISORETRIBUIDO("Horas Permiso Retribuido:"),
    HORASTOTALES("Horas Totales:"),
    IBANDC("IBAN DC:"),
    IBANEXTRANJERO("IBAN Extranjero:"),
    IBANPAIS("IBAN País:"),
    ID("Id:"),
    IMPORTE("Importe:"),
    IMPORTEASEGURADO("Importe Asegurado:"),
    IMPORTEDELAVAL("Importe del Aval:"),
    IMPORTEMAXIMOPORFACTURAIMPORTECORRESPONDIENTEINCLUIDO("Importe Máximo por Factura (Importe Correspondiente Incluido):"),
    IMPUESTOSTIPOPORCENTAJE("Impuestos (Tipo + Porcentaje):"),
    INICIAL("Inicial"),
    INP_ANIO("Año:"),
    INP_TELF1("Telf. 1:"),
    INP_TELF2("Telf. 2:"),
    IT("IT:"),
    LIMITEDERIESGO("Límite de Riesgo:"),
    LIMITEDERIESGODESDE("Límite de Riesgo Desde:"),
    LIMITERIESGO("Límite Riesgo:"),
    LINEAVENTA("Línea Venta:"),
    LKP_ACTIVIDAD("Actividad:"),
    LKP_CNAE("CNAE:"),
    LKP_CONVCOLECTIVOEMPRESAUSUARIA("Conv. Colectivo Empresa Usuaria:"),
    LKP_SIC("SIC:"),
    LOCALIDAD("Localidad:"),
    MARGENBRUTO("Margen Bruto:"),
    MEDIODECAPT("Medio de Capt:"),
    MEDIODECAPTACION("Medio de Captación:"),
    MEDIODEPAGO("Medio de Pago:"),
    MENOR30ANOSREALIZARPRACTICASNOLABORALESRD15432011("Menor 30 años Realizar Prácticas No Laborales (RD 1543/2011):"),
    MOTIVOBAJA("Motivo de la Baja:"),
    MOTIVODESUSTITUCION("Motivo de Sustitución:"),
    NCANDIDATOSASIGNADOS("Nº Candidatos Asignados:"),
    NCANDIDATOSSOLICITADOS("Nº Candidatos Solicitados:"),
    NCLIENTE("Nº Cliente:"),
    NCLIENTE2("Nº Cliente"),
    NCONTRATO("Nº Contrato:"),
    NCTACORRIENTEETT("Nº Cta. Corriente ETT"),
    NCUENTA("Nº Cuenta:"),
    NEMPLEADOS("Nº Empleados:"),
    NIF("NIF:"),
    NIEDNIPASAPORTE("DNI/NIE/Pasaporte:"),
    NIFEMPRESA("NIF Empresa:"),
    NOMBRE("Nombre:"),
    NOMINA("Nómina"),
    NPEDIDO("Nº Pedido:"),
    NPEDIDOAUXILIAR("Nº Pedido Auxiliar:"),
    NPEDIDODESDE("Nº Pedido Desde:"),
    NSOICITUD("Nº Soicitud:"),
    NUMDOCUMENTO("Núm. Documento:"),
    NUMEROCLIENTE("Número Cliente:"),
    NUMERODECLIENTE("Número de Cliente:"),
    NUMEROMAXIMODECOLABORADORESENFACTURA("Número Máximo de Colaboradores en Factura:"),
    OBSERVACIONES("Observaciones:"),
    OCUPACION("Ocupación:"),
    OFERTA("Oferta:"),
    OFICINA("Oficina:"),
    OFICINAORIGENCONTACTO("Oficina Origen Contacto:"),
    OFICINAORIGENDELCONTRATO("Oficina Origen del Contrato:"),
    PAGINAWEB("Página Web:"),
    PERIODODEPRUEBA("Período de Prueba:"),
    PERMISORETRIBUIDO("Permiso Retribuido"),
    PORCENTAGE("%"),
    PORCENTAJEJORNADA("Porcentaje Jornada:"),
    PRECIOVENTA("Precio Venta:"),
    PRESENTAR_INFORME("Presentar Informe"),
    PREVISIONARCOMPENSACIONFINCONTRATO("Previsionar Compensación Fin Contrato"),
    PRIMERAPELLIDO("Primer Apellido:"),
    PROVINCIA("Provincia:"),
    PROVINCIAOFICINA("Provincia Oficina:"),
    PVP("PVP:"),
    QBESEL_DIFERENCIA("Diferencia"),
    QBESEL_TIPO("Tipo"),
    QBESEL_ESTADO("Estado"),
    QBESEL_OFERTA("Oferta"),
    QBE_NCLIENTE("Nº Cliente"),
    QBE_FORMADEPAGO("Forma de Pago"),
    QBE_ESTADO("Estado"),
    QBE_LOG("Log"),
    QBE_LOTE("Lote"),
    QBE_ACCION("Acción"),
    QBE_ESTADO2("Estado2"),
    QBE_NCONTRATO("Nº Contrato"),
    QBE_NUMPROYECT("numProyect"),
    QBE_FECHACREACION("Fecha creación"),
    QBE_FECHAACTUALIZACION("Fecha actualización"),
    QBE_FECHAENVIOAORACLE("Fecha envío a Oracle"),
    QBE_FECHAPROCESADO("Fecha procesado"),
    QBE_USUARIOCREADOR("Usuario creador"),
    QBE_COMPORTAMIENTODEPAGO("Comportamiento de pago"),
    QBE_NPEDIDO("Nº Pedido"),
    QBE_FECHADEINICIO("Fecha de Inicio"),
    QBE_FECHADEFIN("Fecha de Fin"),
    QBE_ACTIVIDAD("Actividad"),
    QBE_C("C"),
    QBE_CARGOCONTACTO("Cargo Contacto"),
    QBE_CATEGORIALABORAL("Categoría Laboral"),
    QBE_CATEGORIAPROFESIONAL("Categoría Profesional"),
    QBE_CENTRODETRABAJO("Centro de Trabajo"),
    QBE_CNAE("CNAE"),
    QBE_CNAE2("C.N.A.E."),
    QBE_CODIGO("Código"),
    QBE_COD_CLI("Cod. Cli."),
    QBE_COEF("Coef"),
    QBE_COEFICIENTE("Coeficiente"),
    QBE_COLABORADOR("Colaborador"),
    QBE_NOMBRE1("Nombre"),
    QBE_CPD_PRO ("Nº CPD / PRO"),
    QBE_SEGURIDADSOCIAL("Seguridad Social"),
    QBE_CONCEPTO("Concepto"),
    QBE_CONCEPTOSDISPONIBLES("Conceptos Disponibles"),
    QBE_CONCEPTOS_F("Conceptos F."),
    QBE_CONCEPTOS_N("Conceptos N."),
    QBE_CONTRATO("Contrato"),
    QBE_COTIZABLE("Cotizable"),
    QBE_CP("CP"),
    QBE_DEVENGO("Devengo"),
    QBE_DIADEFIN("Día de Fin"),
    QBE_DIADEINICIO("Día de Inicio"),
    QBE_DIRECCION("Dirección"),
    QBE_EMPRESA("Empresa"),
    QBE_NROCONTRATO("Nº Contrato"),
    QBE_FEC_GENERACION("Fec. Generación"),
    QBE_FPVP_EXTRA("F.PVP Extra"),
    QBE_FPVP_FEST("F.PVP Fest."),
    QBE_FPVP_NOCT("F.PVP Noct."),
    QBE_F_BAJA("F. Baja"),
    QBE_F_IMPORTE("F. Importe"),
    QBE_F_INICIO("F. Inicio"),
    QBE_FECHA_INICIO("Fec. Inicio"),
    QBE_FECHA_INICIO1("Fecha Inicio"),
    QBE_FECHA_FIN("Fec. Fin"),
    QBE_FECHA_FIN1("Fecha Fin"),
    QBE_FECHA_ENVIO("Fecha Envío"),
    QBE_FECHA_RECEP("Fecha Recep."),
    QBE_FECHA_ANTIGUEDAD("Fec. Antigüedad"),
    QBE_F_SALARIO("F. Salario"),
    QBE_IDACTIVIDAD("ID Actividad"),
    QBE_IDCNAE("ID CNAE"),
    QBE_IDCONTRATO("Id. Contrato"),
    QBE_IDCONTRATO2("ID.Contrato"),
    QBE_IDSIC("ID SIC"),
    QBE_ID_CENT("Id Cent."),
    QBE_IMPORTE("Importe"),
    QBE_MES("Mes"),
    QBE_MOTIVODEBAJA("Motivo de Baja"),
    QBE_MOTIVO_BAJA("Motivo Baja"),
    QBE_NIF("N.I.F."),
    QBE_NIF2("NIF"),
    QBE_NIFEMPRESA("NIF Empresa"),
    QBE_NOMBRE("Nombre"),
    QBE_NOMBRECONTACTO("Nombre Contacto"),
    QBE_NOMBREEMPRESA("Nombre Empresa"),
    QBE_NOMBREOFICINA("Nombre Oficina"),
    QBE_NOMBREYAPELLIDOS("Nombre y Apellidos"),
    QBE_NPARTE("Nº Parte"),
    QBE_NROPARTE("Nº Parte"), //TODO: REVISAR PARA MANTENER NPARTE o NROPARTE SOLAMENTE
    QBE_NS_EXTRA("N.S. Extra"),
    QBE_NS_FEST("N.S. Fest."),
    QBE_NS_NOCT("N.S. Noct."),
    QBE_N_IMPORTE("N. Importe"),
    QBE_N_SALARIO("N. Salario"),
    QBE_OFICINA("Oficina"),
    QBE_PARTEORIGINAL("Parte Original"),
    QBE_PERSONALIZADA("Personalizada"),
    QBE_PRECIO("Precio"),
    QBE_PROVINCIA("Provincia"),
    QBE_RANGOEMPLEADOS("Rango Empleados"),
    QBE_RESPONSABLE("Responsable"),
    QBE_SALARIOUNIDAD("Salario/Unidad"),
    QBE_SEC("Sec."),
    QBE_SIC("SIC"),
    QBE_TELEFONOCONTACTO("Teléfono Contacto"),
    QBE_TOTAL("Total"),
    QBE_TRASPASADO("Traspasado"),
    QBE_UNDS("Unds."),
    QBE_UNDS_EXTRA("Unds. Extra"),
    QBE_UNDS_FESTIVA("Unds. Festiva"),
    QBE_UNDS_NOCTURNA_FAC("Unds.Nocturna Fac"),
    QBE_UNDS_NOCTURNA_NOM("Unds. Nocturna Nom."),
    QBE_UNDS_SALARIO_FAC("Unds. Salario Fac."),
    QBE_UNDS_SALARIO_NOM("Unds. Salario Nom."),
    QBE_UNDS_SALARIO_TEORICO("Unds. Salario Teórico"),
    QBE_UNIDADES("Unidades"),
    QBE_VENTAS("Ventas"),
    RAD_IMPREVISIBLE("Imprevisible"),
    RAD_PREVISIBLE("Previsible"),
    RAD_REALIZANDOELTRASPASODELOSCONTRATOS("Realizando el traspaso de los contratos"),
    RAD_REALIZARLABUSQUEDAANIVELNACIONALNO("No (Dentro de su Oficina)"),
    RAD_REALIZARLABUSQUEDAANIVELNACIONALSI("Sí"),
    RAD_SINTRASPASARCONTRATOS("Sin traspasar los contratos"),
    RANGODEEMPLEADOS("Rango de Empleados:"),
    RAZONSOCIAL("Razón Social:"),
    RAZONSOCIALEMPRESA("Razón Social Empresa:"),
    RAZONSOCIALFACTURA("Razón Social Factura:"),
    REFERENCIA("Referencia:"),
    REGIMENSS("Régimen S.S.:"),
    RESPDECUENTA("Resp. de Cuenta:"),
    RESPONSABLEDECUENTA("Responsable de Cuenta:"),
    REV("Rev:"),
    RIESGO("Riesgo:"),
    RIESGOPEDIDODESDE("Riesgo Pedido Desde:"),
    SALARIAL("Salarial:"),
    SALARIO("Salario:"),
    SECUENCIAL("Secuencial:"),
    SEGUNDOAPELLIDO("Segundo Apellido:"),
    SELECCIONARTITULACION("Seleccionar Titulación"),
    SELECCIONEDURACIONYTIPODEJORNADADELATARIFA("Seleccione Duración y Tipo de Jornada de la Tarifa"),
    SEL_ANIO("Año:"),
    SEL_CONCEPTO("Concepto:"),
    SEL_MES("Mes:"),
    SEL_OFICINA("Oficina:"),
    SEL_PROVINCIA("Provincia:"),
    SEL_REGIMENSDELASEGSOCIAL("Régimen de la Seg.Social:"),
    SEL_ZONA("Zona:"),
    SEL_TIPOIT("Tipo de IT"),
    SEXO("Sexo:"),
    FILTRAR_ESTADO("Filtrar por Estado:"),
    FILTRAR_ESTADO1("Estado"),
    SIC("SIC:"),
    SIGLAS("Siglas:"),
    SUCURSAL("Sucursal:"),
    SUPUESTOCELEBRACION("Supuesto Celebración:"),
    SUSTITUCIONDELTRABAJADOR("Sustitución del Trabajador:"),
    TABCABECERANIF("N.I.F:"),
    TARIFAIGUALOINFERIOR5DIAS("Tarifa Igual o Inferior 5 días"),
    TARIFANORMAL("Tarifa Normal"),
    TCONT("T.Cont."),
    TELEFONO("Teléfono:"),
    TELF1("Telf. 1:"),
    TELF2("Telf. 2:"),
    TIPO("Tipo:"),
    TIPOCONTRATO("Tipo Contrato:"),
    TIPONOVACION("Tipo Novación:"),
    TIPOVIA("Tipo Vía:"),
    TOTAL("TOTAL:"),
    TOTAL2("Total:"),
    TOTALPVP("Total PVP:"),
    TOTALSAL("Total Sal.:"),
    TURNO("Turno"),
    UNIDADES("Unidades:"),
    UNIDADESEXTRA("Unidades Extra:"),
    VENTAS("Ventas:");

    private final String codigo;

    FieldByTagLabelText(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }

}

