package com.eulen.flexinet.core.test.selenium.Locators;

public enum MenuByTextContent {
    ADMINISTRACIONDEFLEXINET("ADMINISTRACIÓN DE FLEXINET"),
    GestiondeUsuarios("Gestión de Usuarios"),
    Alta("Alta"),
    ConsultadeUsuarios("Consulta de Usuarios"),
    GestiondeTablas("Gestión de Tablas"),
    GestiondeUsuariosPortaldeClientes("Gestión de Usuarios Portal de Clientes"),
    AltasUsuariosPortaldeClientes("Altas Usuarios Portal de Clientes"),
    ConsultaUsuariosPortaldeClientes("Consulta Usuarios Portal de Clientes"),
    InformeExpiracionCertificados("Informe Expiración Certificados"),
    MantenimientoAcuerdosNacionales("Mantenimiento Acuerdos Nacionales"),
    ExportaciondeTablasMaestras("Exportación de Tablas Maestras"),
    ImportaciondeTablasMaestras("Importación de Tablas Maestras"),
    GestiondeCostes("Gestión de Costes"),
    GestiondeCostesSEA("Gestión de Costes SEA"),
    SincronizaciondeCursosdePrevencion("Sincronización de Cursos de Prevención"),
    Procesosejecutables("Procesos ejecutables"),
    RIESGOS("RIESGOS"),
    ConsultadePedidosVigentes("Consulta de Pedidos Vigentes"),
    GestiondePedidosBloqueados("Gestión de Pedidos Bloqueados"),
    GestiondeSolicitudes("Gestión de Solicitudes"),
    GestiondeEmpresas("Gestión de Empresas"),
    InformePedidosBloqueados("Informe Pedidos Bloqueados"),
    GestionCuentasFlexiplan("Gestión Cuentas Flexiplán"),
    GESTIONDEOFICINAS("GESTIÓN DE OFICINAS"),
    GestiondeEmpresasCliente("Gestión de Empresas Cliente"),
    Consulta("Consulta"),

    TraspasosMasivosDeAltas("Traspasos Masivos de Altas"),
    GestiondeClientesContrato("Gestión de Clientes-Contrato"),
    GestiondeCentrosdeTrabajo("Gestión de Centros de Trabajo"),
    GestiondecursosdePrevencion("Gestión de cursos de Prevención"),
    Pedidos("Pedidos"),
    Simple("Simple"),
    Indefinidos("Indefinidos"),
    PedidosLV3233("Pedidos LV 32-33"),
    GestiondeSolicitudesdelPortaldeClientes("Gestión de Solicitudes del Portal de Clientes"),
    Contratos("Contratos"),
    Anulacion("Anulación"),
    Sustitucion("Sustitución"),
    AltaSustitucion("Sustitución Alta"),
    ControlEnviosCpds("Control Envíos CPDS"),
    Prorrogas("Prórrogas"),
    ProrrogasAnulacion("Prórrogas Anulación"),
    Novacion("Novación"),
    Suspension("Suspensión"),
    Baja("Baja"),
    DardeBaja("Dar de Baja"),
    BajasMasivas("Bajas Masivas"),
    ControlEnviosCPDS("Control Envíos CPDS"),
    SeguimientoExpedienteVirtual("Seguimiento Expediente Virtual"),
    TraspasosMasivosdeAltas("Traspasos Masivos de Altas"),
    PartesdeHoras("Partes de Horas"),
    Traspaso("Traspaso"),
    Facturacion("Facturación"),
    EmisiondeFacturaGlobalizada("Emisión de Factura Globalizada"),
    SolicitudLineasdeRegularizacion("Solicitud Lineas de Regularizacion "),
    ObtenerPlantillas("Obtener Plantillas"),
    SolicituddePrefacturacion("Solicitud de Prefacturación"),
    GestionPresupuestaria("Gestión Presupuestaria"),
    PresupuestoExplotacion("Presupuesto Explotación"),
    PresupuestoCostesIndirectos("Presupuesto Costes Indirectos"),
    SimulacionPresupuestaria("Simulación Presupuestaria"),
    FirmaElectronica("Firma Electrónica"),
    ContratosCPDyProrrogasCPDyProrrogas("Contratos (CPD) y Prórrogas"),
    Facturas("Facturas"),
    ExpedienteVirtual("Expediente Virtual"),
    GestiondeIncorporaciondeContratosaFirma("Gestión de Incorporación de Contratos a Firma"),
    GestionDocumental("Gestión Documental"),
    GestiondeMandatos("Gestión de Mandatos"),
    AgenciasColocacion("Agencias Colocación"),
    SEPE("SEPE"),
    Seguimiento("Seguimiento"),
    GestiondeOrdenesdeFacturacion("Gestión de Órdenes de Facturación"),
    GestiondeEmbargos("Gestión de Embargos"),
    GestiondeAtrasosenConvenios("Gestión de Atrasos en Convenios"),
    ConsultadeITs("Consulta de ITs"),
    GESTIONDEABONOS("GESTIÓN DE ABONOS"),
    AbonodeFactura("Abono de Factura"),
    GESTIONAVANZADA("GESTIÓN AVANZADA"),
    FacturacionManual("Facturación Manual"),
    CreaciondePrefactura("Creación de Prefactura"),
    EnviosdeFacturaE("Envíos de FacturaE"),
    EnvioPartesAOracle("Envío Partes a Oracle"),
    DetalleFacturaElectronica("Detalle Factura Electrónica"),
    BloqueodeFacturacionActiva("Bloqueo de Facturación Activa"),
    IntroducciondelPeriododeBloqueo("Introducción del Período de Bloqueo"),
    GestiondeDocumentos("Gestión de Documentos"),
    GestiondePlantillas("Gestión de Plantillas"),
    GestiondeClausulas("Gestión de Cláusulas"),
    NormasyProcedimientosGenerales("Normas y Procedimientos Generales"),
    MantenimientodePresupuestosAnuales("Mantenimiento de Presupuestos Anuales"),
    GestionPresupuestosEnviados("Gestión Presupuestos Enviados"),
    MarcarPartesComoFacturados("Marcar Partes Como Facturados"),
    MantenimientoDigitalizaciondeClientes("Mantenimiento Digitalización de Clientes"),
    DatoUnico("Dato Único"),
    Afiliacion("Afiliación"),
    SelecciondeContratos("Selección de Contratos"),
    ConsultayAnulaciondeEnvios("Consulta y Anulación de Envíos"),
    Contrat("Contrat@"),
    TraspasosMasivosDeContratos("Traspasos Masivos De Contratos"),
    TraspasosMasivosdeBajas("Traspasos Masivos de Bajas"),
    GeneracionMasivadePartes("Generación Masiva de Partes"),
    ConsultaAvanzadadePartesdeHoras("Consulta Avanzada de Partes de Horas"),
    GestiondeSPFs("Gestión de SPFs"),
    FacturaciondeSPFs("Facturación de SPFs"),
    AnulaciondeSPFs("Anulación de SPFs"),
    InformedeMaximos("Informe de Máximos"),
    InformedeFiniquitosPendientes("Informe de Finiquitos Pendientes"),
    PrefacturacionOrdenesdeFacturacion("Prefacturación Órdenes de Facturación"),
    SPFsFlexinet("SPFs Flexinet"),
    Informedepartesconembargos("Informe de partes con embargos"),
    ADMINISTRACIONDEPERSONAL("ADMINISTRACIÓN DE PERSONAL"),
    BasesdeCotizacion("Bases de Cotización"),
    GestionSolicitudesBasesdeCotizacion("Gestión Solicitudes Bases de Cotización"),
    IntroduccionBasesdeCotizacion("Introducción Bases de Cotización"),
    InformesITs("Informes ITs"),
    GestiondeITs("Gestión de ITs"),
    GESTIONDEINFORMES("GESTIÓN DE INFORMES"),
    InformesdeContratacionyPersonal("Informes de Contratación y Personal"),
    ListadodeCPDS("Listado de CPDS"),
    AGETT("AGETT"),
    ListadodeNominas("Listado de Nóminas"),
    InformeControldeNominasyFiniquitos("Informe Control de Nóminas y Finiquitos"),
    InformeDigitalparaCierredeNomina("Informe Digital para Cierre de Nómina"),
    InformedeContratacionyFacturacion("Informe de Contratación y Facturación"),
    InformedeContratacionyPersonal("Informe de Contratación y Personal"),
    InformedeAbsentismo("Informe de Absentismo"),
    ControldeTemporalidad("Control de Temporalidad"),
    InformedeAlarmas("Informe de Alarmas"),
    GestiondeFijosDiscontinuos("Gestión de Fijos Discontinuos"),
    InformesdeFacturacion("Informes de Facturación"),
    InformedeClientesPendientesdeFactura("Informe de Clientes Pendientes de Factura"),
    InformedeLineasdeRegularizacion("Informe de Líneas de Regularización "),
    InformeOrdenesdeFacturacion("Informe Órdenes de Facturación"),
    InformedeFacturacion("Informe de Facturación"),
    HorasTeoricasporCliente("Horas Teóricas por Cliente"),
    InformesdeControlGeneral("Informes de Control General"),
    VentasAcumuladasporClienteContrato("Ventas Acumuladas por Cliente-Contrato"),
    ClientesconReciboDomiciliado("Clientes con Recibo Domiciliado"),
    ConceptosenNominaporOficina("Conceptos en Nómina por Oficina"),
    SeguimientodelTrabajoporOficina("Seguimiento del Trabajo por Oficina"),
    InformeClientesNuevos("Informe Clientes Nuevos"),
    InformeContratacionyVentasAnuales("Informe Contratación y Ventas Anuales"),
    VentasAcumuladasporClienteContratoMensual("Ventas Acumuladas por Cliente Contrato Mensual"),
    InformePlanningdeActividad("Informe Planning de Actividad"),
    InformeControlEnviosCPDS("Informe Control Envíos CPDS"),
    ControlMargenes("Control Márgenes"),
    InformeINE("Informe I.N.E"),
    InformesdeCuadrodeMandos("Informes de Cuadro de Mandos"),
    ControlPresupuestariodeVentas("Control Presupuestario de Ventas"),
    CuadrodeMandosdeActividad("Cuadro de Mandos de Actividad"),
    InformesdeGrandesCuentas("Informes de Grandes Cuentas"),
    ListadodeAcuerdosNacionales("Listado de Acuerdos Nacionales"),
    InformesdeCalidad("Informes de Calidad"),
    IndicadoresdeActividaddeGestion("Indicadores de Actividad de Gestión");

    private final String codigo;

    MenuByTextContent(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }

}
